export const dummyCoffeeData = [
  {
    productName: "Arabica Coffee Beans",
    manufacturer: "Bean Masters",
    itemNumber: "CM001",
    category: "Coffee Beans",
    problemCondition: "Freshly Roasted",
    quantity: 100,
    pricePerUnit: 12.99,
    expiryDate: "01/01/2025",
  },
  {
    productName: "Espresso Blend",
    manufacturer: "BrewHub",
    itemNumber: "CM002",
    category: "Coffee Blend",
    problemCondition: "Ground and Packed",
    quantity: 50,
    pricePerUnit: 9.99,
    expiryDate: "15/03/2025",
  },
  {
    productName: "French Press Kit",
    manufacturer: "Cafe Essentials",
    itemNumber: "CM003",
    category: "Brewing Equipment",
    problemCondition: "New in Box",
    quantity: 30,
    pricePerUnit: 24.99,
    expiryDate: "10/06/2025",
  },
  {
    productName: "Cold Brew Concentrate",
    manufacturer: "ChillBrew",
    itemNumber: "CM004",
    category: "Cold Brew",
    problemCondition: "Ready to Mix",
    quantity: 80,
    pricePerUnit: 16.49,
    expiryDate: "05/02/2025",
  },
  {
    productName: "Cappuccino Cups Set",
    manufacturer: "CeramicCraft",
    itemNumber: "CM005",
    category: "Coffee Accessories",
    problemCondition: "Dishwasher Safe",
    quantity: 40,
    pricePerUnit: 19.99,
    expiryDate: "20/07/2025",
  },
  {
    productName: "Mocha Syrup",
    manufacturer: "SweetSips",
    itemNumber: "CM006",
    category: "Coffee Syrups",
    problemCondition: "Sugar-Free",
    quantity: 60,
    pricePerUnit: 8.99,
    expiryDate: "12/04/2025",
  },
  {
    productName: "Single-Origin Sampler",
    manufacturer: "Global Beans",
    itemNumber: "CM007",
    category: "Coffee Sampler",
    problemCondition: "Variety Pack",
    quantity: 25,
    pricePerUnit: 14.99,
    expiryDate: "30/09/2025",
  },
  {
    productName: "Coffee Grinder",
    manufacturer: "GrindMaster",
    itemNumber: "CM008",
    category: "Brewing Equipment",
    problemCondition: "Adjustable Settings",
    quantity: 15,
    pricePerUnit: 34.99,
    expiryDate: "25/11/2025",
  },
  {
    productName: "Latte Art Stencils",
    manufacturer: "ArtisticBeans",
    itemNumber: "CM009",
    category: "Coffee Accessories",
    problemCondition: "Reusable",
    quantity: 50,
    pricePerUnit: 7.49,
    expiryDate: "08/03/2025",
  },
  {
    productName: "Decaf Coffee Pods",
    manufacturer: "SilentBrew",
    itemNumber: "CM010",
    category: "Coffee Pods",
    problemCondition: "Individually Wrapped",
    quantity: 70,
    pricePerUnit: 11.99,
    expiryDate: "18/12/2025",
  },
  {
    productName: "Coffee Brewing Scale",
    manufacturer: "PrecisionPour",
    itemNumber: "CM011",
    category: "Brewing Equipment",
    problemCondition: "LCD Display",
    quantity: 20,
    pricePerUnit: 29.99,
    expiryDate: "22/05/2025",
  },
  {
    productName: "Irish Cream Flavoring",
    manufacturer: "LiquorFlavors",
    itemNumber: "CM012",
    category: "Coffee Flavors",
    problemCondition: "Non-Alcoholic",
    quantity: 40,
    pricePerUnit: 6.99,
    expiryDate: "02/08/2025",
  },
  {
    productName: "Coffee Mug Set",
    manufacturer: "MugMagic",
    itemNumber: "CM013",
    category: "Coffee Accessories",
    problemCondition: "Microwave Safe",
    quantity: 35,
    pricePerUnit: 17.99,
    expiryDate: "14/10/2025",
  },
  {
    productName: "Vietnamese Coffee Drip",
    manufacturer: "SaigonBrew",
    itemNumber: "CM014",
    category: "Brewing Equipment",
    problemCondition: "Stainless Steel",
    quantity: 25,
    pricePerUnit: 21.99,
    expiryDate: "07/06/2025",
  },
  {
    productName: "Coffee Tumbler",
    manufacturer: "TasteOnTheGo",
    itemNumber: "CM015",
    category: "Travel Accessories",
    problemCondition: "Leak-Proof",
    quantity: 30,
    pricePerUnit: 12.49,
    expiryDate: "28/01/2025",
  },
  {
    productName: "Hazelnut Coffee Beans",
    manufacturer: "NutsnBeans",
    itemNumber: "CM016",
    category: "Flavored Coffee",
    problemCondition: "Whole Bean",
    quantity: 50,
    pricePerUnit: 13.99,
    expiryDate: "19/04/2025",
  },
  {
    productName: "Coffee Chemex Set",
    manufacturer: "BrewAlchemy",
    itemNumber: "CM017",
    category: "Brewing Equipment",
    problemCondition: "Wood Collar",
    quantity: 15,
    pricePerUnit: 39.99,
    expiryDate: "11/09/2025",
  },
  {
    productName: "Iced Coffee Pitcher",
    manufacturer: "ChillPitch",
    itemNumber: "CM018",
    category: "Cold Brew",
    problemCondition: "BPA-Free",
    quantity: 20,
    pricePerUnit: 19.99,
    expiryDate: "23/03/2025",
  },
  {
    productName: "Coffee Scoop Set",
    manufacturer: "MeasureMasters",
    itemNumber: "CM019",
    category: "Coffee Accessories",
    problemCondition: "Stainless Steel",
    quantity: 40,
    pricePerUnit: 5.99,
    expiryDate: "16/07/2025",
  },
  {
    productName: "Caramel Macchiato Pods",
    manufacturer: "CaramelCraft",
    itemNumber: "CM020",
    category: "Coffee Pods",
    problemCondition: "Compatible with Keurig",
    quantity: 60,
    pricePerUnit: 14.49,
    expiryDate: "04/12/2025",
  },
  {
    productName: "Mocha Syrup",
    manufacturer: "SweetSips",
    itemNumber: "CM006",
    category: "Coffee Syrups",
    problemCondition: "Sugar-Free",
    quantity: 60,
    pricePerUnit: 8.99,
    expiryDate: "12/04/2025",
  },
  {
    productName: "Hazelnut Coffee Beans",
    manufacturer: "NutsnBeans",
    itemNumber: "CM016",
    category: "Flavored Coffee",
    problemCondition: "Whole Bean",
    quantity: 50,
    pricePerUnit: 13.99,
    expiryDate: "19/04/2025",
  },
];
